Repository econ-ark/HARK, pull requests merged in 2019-05, with the labels that each got.

#272 Add "Learning HARK" section to README
  README.md
Labels: documentation

#284 Moved checkConditions out of init
  HARK/ConsumptionSaving/ConsAggShockModel.py
  HARK/ConsumptionSaving/ConsGenIncProcessModel.py
  HARK/ConsumptionSaving/ConsIndShockModel.py
  HARK/ConsumptionSaving/ConsMarkovModel.py
  HARK/ConsumptionSaving/ConsMedModel.py
  HARK/ConsumptionSaving/ConsPrefShockModel.py
  HARK/ConsumptionSaving/ConsRepAgentModel.py
Labels: for hark 2.0, needs discussion

#258 Gauss Hermite-based normal and lognormal quadrature nodes and weights
  HARK/tests/test_approxDstns.py
  HARK/utilities.py
Labels: enhancement
