Repository econ-ark/HARK, pull requests merged in 2022-08, with the labels that each got.

#1156 Faster Expectations and new DiscreteDistributionXRA class
  Documentation/CHANGELOG.md
  HARK/ConsumptionSaving/ConsIndShockModel.py
  HARK/ConsumptionSaving/ConsMarkovModel.py
  HARK/distribution.py
  HARK/tests/test_distribution.py
  examples/Distributions/DiscreteDistributionXRA.ipynb
  examples/Distributions/DiscreteDistributionXRA.py
  examples/Distributions/ExpectedValue.ipynb
  examples/Distributions/ExpectedValue.py
  requirements.txt
  setup.cfg
Labels: Type: Enhancement, Status: In Progress, Tag: New Tool, Function: Distributions

#1157 Gradients/derivatives in econforge interpolators
  Documentation/CHANGELOG.md
  HARK/econforgeinterp.py
  HARK/interpolation.py
  HARK/tests/test_econforgeinterp.py
Labels: Status: Review Needed, Ready-To-Merge

#1154 Documentation fix AMonninger
  Documentation/ARKitecture.md
  Documentation/conf.py
  Documentation/contributing/CONTRIBUTING.md
  Documentation/example_notebooks/HARK_struct_2.png
  Documentation/example_notebooks/HARK_struct_3.png
  Documentation/example_notebooks/HARK_struct_4.png
  Documentation/index.rst
  Documentation/introduction.md
  Documentation/quick-start.md
  Documentation/reference/ConsumptionSaving/ConsPortfolioFrameModel.rst
  Documentation/reference/ConsumptionSaving/ConsRiskyAssetModel.rst
  Documentation/reference/ConsumptionSaving/ConsRiskyContribModel.rst
  Documentation/reference/ConsumptionSaving/index.rst
  Documentation/reference/tools/econforgeinterp.rst
  Documentation/reference/tools/frame.rst
  Documentation/reference/tools/index.rst
  Documentation/reference/tools/numba.rst
  README.md
  examples/ConsIndShockModel/IndShockConsumerType.ipynb
  examples/ConsIndShockModel/IndShockConsumerType.py
  examples/ConsIndShockModel/KinkedRconsumerType.ipynb
  examples/ConsIndShockModel/KinkedRconsumerType.py
  examples/ConsIndShockModel/PerfForesightConsumerType.ipynb
  examples/ConsIndShockModel/PerfForesightConsumerType.py
  examples/ConsPortfolioModel/example_ConsPortfolioModel.ipynb
  examples/ConsPortfolioModel/example_ConsPortfolioModel.py
  examples/ConsPortfolioModel/example_ConsSequentialPortfolioModel.ipynb
  examples/ConsPortfolioModel/example_ConsSequentialPortfolioModel.py
  examples/ConsumptionSaving/example_ConsAggShockModel.ipynb
  examples/ConsumptionSaving/example_TractableBufferStockModel.ipynb
  examples/GenIncProcessModel/GenIncProcessModel.ipynb
  examples/GenIncProcessModel/GenIncProcessModel.py
  examples/Gentle-Intro/Gentle-Intro-To-HARK.ipynb
  examples/Gentle-Intro/Gentle-Intro-To-HARK.py
  examples/HowWeSolveIndShockConsumerType/HowWeSolveIndShockConsumerType.ipynb
  examples/HowWeSolveIndShockConsumerType/HowWeSolveIndShockConsumerType.py
  examples/Journeys/Journey_1_PhD.ipynb
  examples/Journeys/Quickstart_tutorial/Quick_start_with_solution.ipynb
  examples/LifecycleModel/LifecycleModel.ipynb
  examples/LifecycleModel/LifecycleModel.py
Labels: Ready-To-Merge
