Repository econ-ark/HARK, pull requests merged in 2022-10, with the labels that each got.

#1155 Transition Matrix Methods
  Documentation/CHANGELOG.md
  HARK/ConsumptionSaving/ConsIndShockModel.py
  HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
  HARK/utilities.py
  examples/ConsIndShockModel/IndShockConsumerType_Transition_Matrix_Example.ipynb
Labels: Status: Review Needed, TSC: Review Needed, automerge

#1170 Changes to DiscreteDistributionXRA
  Documentation/CHANGELOG.md
  HARK/distribution.py
  HARK/tests/test_distribution.py
  examples/Distributions/DiscreteDistributionLabeled.ipynb
  examples/Distributions/DiscreteDistributionLabeled.py
Labels: automerge, Ready-To-Merge

#1174 Documentation fix AMonninger
  Documentation/ARKitecture.md
  Documentation/_static/HARKmanual.pdf
  Documentation/contributing/CONTRIBUTING.md
  Documentation/introduction.md
  Documentation/quick-start.md
  examples/Journeys/Journey_1_PhD.ipynb
Labels: Ready-To-Merge

#1181 [Bug-fix] Mortality and `t_cycle` when shocks are read
  Documentation/CHANGELOG.md
  HARK/Calibration/Income/IncomeTools.py
  HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
  HARK/core.py
Labels: Ready-To-Merge

#1184 Add seed as property of DiscreteDstnLabeled
  Documentation/CHANGELOG.md
  HARK/distribution.py
Labels: Ready-To-Merge
