Repository econ-ark/HARK, pull requests merged in 2025-04, with the labels that each got.

#1543 Start solver from arbitrary solution object
  Documentation/CHANGELOG.md
  HARK/core.py
  HARK/tests/test_core.py
Labels: Status: Review Needed

#1546 Small fixes to simulator methods
  HARK/ConsumptionSaving/ConsMarkovModel.py
  HARK/ConsumptionSaving/ConsPortfolioModel.py
  HARK/ConsumptionSaving/ConsRiskyAssetModel.py
Labels: Priority: High, Status: Review Needed, Version: 0.16

#1544 Use "from_solution" solves in NKAgent
  HARK/ConsumptionSaving/ConsNewKeynesianModel.py
Labels: Version: 0.16
