Repository econ-ark/HARK, pull requests merged in 2025-05, with the labels that each got.

#1529 Unwind init dependencies
  HARK/Calibration/Assets/AssetProcesses.py
  HARK/ConsumptionSaving/ConsAggShockModel.py
  HARK/ConsumptionSaving/ConsBequestModel.py
  HARK/ConsumptionSaving/ConsGenIncProcessModel.py
  HARK/ConsumptionSaving/ConsIndShockModel.py
  HARK/ConsumptionSaving/ConsIndShockModelFast.py
  HARK/ConsumptionSaving/ConsLabeledModel.py
  HARK/ConsumptionSaving/ConsLaborModel.py
  HARK/ConsumptionSaving/ConsMarkovModel.py
  HARK/ConsumptionSaving/ConsMedModel.py
  HARK/ConsumptionSaving/ConsNewKeynesianModel.py
  HARK/ConsumptionSaving/ConsPortfolioModel.py
  HARK/ConsumptionSaving/ConsPrefShockModel.py
  HARK/ConsumptionSaving/ConsRepAgentModel.py
  HARK/ConsumptionSaving/ConsRiskyAssetModel.py
  HARK/ConsumptionSaving/ConsRiskyContribModel.py
  HARK/ConsumptionSaving/ConsWealthPortfolioModel.py
  HARK/ConsumptionSaving/TractableBufferStockModel.py
  HARK/ConsumptionSaving/tests/test_ConsAggShockModel.py
  HARK/ConsumptionSaving/tests/test_ConsLabeledModel.py
  HARK/ConsumptionSaving/tests/test_ConsPortfolioModel.py
  HARK/ConsumptionSaving/tests/test_ConsRiskyContribModel.py
  HARK/ConsumptionSaving/tests/test_IndShockConsumerTypeFast.py
  HARK/core.py
  examples/ConsPortfolioModel/example_ConsPortfolioModel.ipynb
  examples/ConsumptionSaving/example_ConsRepAgentModel.ipynb
  examples/ConsumptionSaving/example_ConsRiskyContribModel.ipynb
  examples/LabeledModels/LabeledModels.ipynb
Labels: Status: Review Needed, Version: 0.17

#1530 Remove update_Rfree()
  HARK/ConsumptionSaving/ConsBequestModel.py
  HARK/ConsumptionSaving/ConsGenIncProcessModel.py
  HARK/ConsumptionSaving/ConsIndShockModel.py
  HARK/ConsumptionSaving/ConsIndShockModelFast.py
  HARK/ConsumptionSaving/ConsLaborModel.py
  HARK/ConsumptionSaving/ConsMarkovModel.py
  HARK/ConsumptionSaving/ConsMedModel.py
  HARK/ConsumptionSaving/ConsNewKeynesianModel.py
  HARK/ConsumptionSaving/ConsPortfolioModel.py
  HARK/ConsumptionSaving/ConsPrefShockModel.py
  HARK/ConsumptionSaving/ConsRiskyAssetModel.py
  HARK/ConsumptionSaving/ConsRiskyContribModel.py
  HARK/ConsumptionSaving/ConsWealthPortfolioModel.py
  HARK/ConsumptionSaving/tests/test_ConsGenIncProcessModel.py
  HARK/ConsumptionSaving/tests/test_ConsMarkovModel.py
  HARK/ConsumptionSaving/tests/test_ConsRiskyContribModel.py
  HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
  HARK/ConsumptionSaving/tests/test_IndShockConsumerTypeFast.py
  HARK/ConsumptionSaving/tests/test_PerfForesightConsumerType.py
  HARK/ConsumptionSaving/tests/test_PerfForesightFastConsumerType.py
  HARK/ConsumptionSaving/tests/test_modelcomparisons.py
  HARK/core.py
  HARK/tests/test_core.py
  examples/ConsBequestModel/example_TerminalBequest.ipynb
  examples/ConsBequestModel/example_TerminalBequestPort.ipynb
  examples/ConsBequestModel/example_WarmGlowBequest.ipynb
  examples/ConsBequestModel/example_WarmGlowBequestPort.ipynb
  examples/ConsBequestModel/example_WealthPortfolio.ipynb
  examples/ConsIndShockModel/Finite Cyclical Test.ipynb
  examples/ConsIndShockModel/IndShockConsumerType.ipynb
  examples/ConsIndShockModel/PerfForesightConsumerType.ipynb
  examples/ConsNewKeynesianModel/HANKFiscal_example.ipynb
  examples/ConsNewKeynesianModel/KS-HARK-presentation.ipynb
  examples/ConsNewKeynesianModel/Transition_Matrix_Example.ipynb
  examples/ConsPortfolioModel/example_ConsPortfolioModel.ipynb
  examples/ConsPortfolioModel/example_ConsSequentialPortfolioModel.ipynb
  examples/ConsumptionSaving/example_ConsIndShock.ipynb
  examples/ConsumptionSaving/example_ConsMarkovModel.ipynb
  examples/ConsumptionSaving/example_ConsRiskyContribModel.ipynb
  examples/ConsumptionSaving/example_TractableBufferStockModel.ipynb
  examples/Estimation/Method of Simulated Moments.ipynb
  examples/GenIncProcessModel/GenIncProcessModel.ipynb
  examples/Gentle-Intro/Gentle-Intro-To-HARK.ipynb
  examples/HowWeSolveIndShockConsumerType/HowWeSolveIndShockConsumerType.ipynb
  examples/Journeys/Journey-Policymaker.ipynb
  examples/Journeys/Quickstart_tutorial/Quick_start_with_solution.ipynb
  examples/LabeledModels/LabeledModels.ipynb
  examples/LifecycleModel/Cycles_tutorial.ipynb
  examples/LifecycleModel/EstimationParameters.py
  examples/LifecycleModel/LifecycleModel.ipynb
Labels: Status: Review Needed, Version: 0.16

#1524 Reproduce PR #1479
  Documentation/CHANGELOG.md
  HARK/Calibration/Income/IncomeProcesses.py
  HARK/ConsumptionSaving/ConsIndShockModel.py
  HARK/ConsumptionSaving/tests/test_ConsNewKeynesianModel.py
  HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
  HARK/ConsumptionSaving/tests/test_modelcomparisons.py
  HARK/distributions/base.py
  HARK/distributions/continuous.py
  HARK/distributions/discrete.py
  HARK/distributions/multivariate.py
  HARK/distributions/utils.py
Labels: Priority: High, Status: Review Needed, Version: 0.16

#1555 Fix Monte Carlo distribution assertion
  HARK/distributions/utils.py
Labels: codex

#1556 Fix typo in core error message
  HARK/core.py
Labels: codex

#1557 Fix 'paramaters' typos
  HARK/ConsumptionSaving/tests/test_IndShockConsumerType.py
  README.md
  examples/ConsIndShockModel/Finite Cyclical Test.ipynb
  examples/ConsIndShockModel/IndShockConsumerType.ipynb
  examples/ConsIndShockModel/KinkedRconsumerType.ipynb
  examples/LifecycleModel/Cycles_tutorial.ipynb
Labels: codex

#1558 Use assert_allclose in tests
  HARK/simulation/test_monte_carlo.py
Labels: codex

#1560 Improve timing docs
  Documentation/overview/ARKitecture.md
  README.md
Labels: codex

#1561 Enable parallel simulation for AgentPopulation
  HARK/core.py
Labels: codex

#1559 Fix calibration mutation in Monte Carlo
  HARK/simulation/monte_carlo.py
  HARK/simulation/test_monte_carlo.py
Labels: codex

#1562 Improve numpy usage
  HARK/ConsumptionSaving/ConsIndShockModel.py
  HARK/core.py
  HARK/utilities.py
Labels: codex

#1564 Replicates Qatar airways edits #1480
  examples/ConsNewKeynesianModel/HANKFiscal_example.ipynb
  examples/ConsNewKeynesianModel/SSJ_explanation.ipynb
Labels: Priority: High, Version: 0.16
